In [5]:
import numpy as np

# 4 points in 3D space
points = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])  # shape (4, 3)

# Sum along last axis (each point)
print(np.sum(points, axis=-1))
print(np.sum(points, axis=0))
print(np.sum(points, axis=1))

[ 6 15 24 33]
[22 26 30]
[ 6 15 24 33]
